 language: python # => 1

    python: # => 2

      - "3.5"

      - "3.6"

    services: # => 3

      - postgresql

    env: # => 4

      -DJANGO=2.0.9 DB=postgresql
    install: # => 5

      - pip install -r requirements.txt

    script: # => 7

      - python manage.py test
