 language: python # => 1

    python: # => 2

      - "3.5"

      - "3.6"

    services: # => 3

      - postgresql

    env: # => 4

      -DJANGO=2.0.9 DB=postgresql
    install: # => 5

      - pip install -r requirements.txt

    before_script:

      - psql -c 'create database portal;' -U postgres

    script: # => 7

      - python manage.py test

    notifications:

      slack: 'moringaschool:u8hH6SAUSdH2imWTFwM2e03G'
      on_success: never # default: always
      on_failure: always # default: always
